### ISSUE TITLE
update

### ISSUE THREAD

**Issue by veratone** [reuke/FaceAppDesktop#5]
Обнову хочет брат

**Comment by reuke** [comment]
[Добавил](https://github.com/reuke/FaceAppDesktop/releases/tag/v0.2) поддержку API v3.
Старое API второй версии иногда работает, но не всегда. Третья версия имеет жесткие ограничения на количество запросов. Я добавил переключатель чтобы не загружать все фильтры сразу. Но я не уверен основано ли ограничение третьй версии на количестве загруженных фоток или скачанных отфильтрованных. Так что может быть использовать его и нет смысла.
